### ISSUE TITLE
@DbArray with Set<out XXX> does not work

### ISSUE THREAD

**Issue by tobias-** [ebean-orm/kotlin-querybean-generator#23]
#### Setup
Creating a Kotlin property like this causes generator to generate invalid Kotlin code:
```kotlin
@DbArray
var myArray: Set<MyEnum> = listOf()
```

#### What happens
which will look like:
```kotlin
package com.example;

import ? extends com.example.MyEnum;
```

#### Why
The reason is that the bytecode will look like below because of Kotlins implicit `out` keyword (same as `? extends ` in Java)
```
  private java.util.Set<? extends com.example.MyEnum> myArray;
```
#### Workaround 
There are two workaround. either make the `Set` a `MutableSet` or annotate it with `@JvmSuppressWildcards` like so:
```
@DbArray
@JvmSuppressWildcards
var myArray: Set<MyEnum> = listOf()
```

**Comment by tobias-** [comment]
@rbygrave *nudge*

The error is only seen when the variable is mutable (`var`)

**Comment by rbygrave** [comment]
Are you preparing a PR?

**Comment by tobias-** [comment]
I tried to, but I couldn't figure out how to do tests in this project. Haven't given up yet though.

If you just need a example project, I can provide that pretty easily.
