### ISSUE TITLE
[Question]: query bean fields for custom type.

### ISSUE THREAD

**Issue by adrian5632** [ebean-orm/kotlin-querybean-generator#6]
Is it possible to somehow force querybean generator to generate fields for custom types (for example I am using DateTime from korlibs/klock as primary class for date/datetime objects; I have my own class extending ScalarTypeBaseDate)?

So if I for example have a test model:
```
import com.soywiz.klock.DateTime
import io.ebean.Model
import java.util.*
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

@Table
@Entity
class TestModel : Model() {
    @Id
    var id: Long = 0L

    @Column(columnDefinition = "DATETIME")
    var date: DateTime? = DateTime.now()

    @Column(columnDefinition = "DATETIME")
    var date2: Date? = Date()
}
```

Saving the model works fine, but querybean generator only generates field for date2 (but not for date). I am using jooby / gradle / kotlin configuration.

**Comment by rbygrave** [comment]
Not at the moment.  I think it would need to read some extra resource (properties or manifest file) which would tell it the types to map.

Something like that I think.

**Comment by rbygrave** [comment]
If you look at line: https://github.com/ebean-orm/kotlin-querybean-generator/blob/master/src/main/java/io/ebean/querybean/generator/PropertyTypeMap.java#L96

I believe it would work to fork this repo and add a line like:
```java
    map.put("com.soywiz.klock.DateTime", new PropertyType("PTimestamp"));

// or ... map it to PInstant or some other javax.time type 

    map.put("com.soywiz.klock.DateTime", new PropertyType("PInstant"));

```

**Comment by rbygrave** [comment]
Not sure if you tried that @adrian5632  but I'll close this now.
